name: flapper - gha ci

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - "master"

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.4

      - name: Debug git metadata
        run: |
          echo "Branch: ${{ steps.branch-name.outputs.current_branch }} Tag: ${{ steps.branch-name.outputs.tag }} Commit: $GITHUB_SHA"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker metadata for GHCR
        id: ghcrmeta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/jsbaudler/flapper
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ steps.ghcrmeta.outputs.tags }}
          labels: ${{ steps.gcrmeta.outputs.labels }}
